### ISSUE TITLE
REQUIREMENTS.txt

### ISSUE THREAD

**Issue by VertigoRay** [MatthewT1/showTimeTexter#1]
Good stuff, Matt!! 

Instead of putting your requirements in the README, consider creating a REQUIREMENTS.txt with `pip freeze`.  [More info](https://pip.readthedocs.org/en/1.1/requirements.html#freezing-requirements).

Of course, this works best if you have a clean install of python on your system and do all of your development work in virtualenvs.

**Comment by MatthewT1** [comment]
Thanks for the suggestion! Didn't know there was an easy way to do that - I just added stable-req.txt and updated the readme.
